### ISSUE TITLE
Wondering if any possiblity to support IOS as well?

### ISSUE THREAD

**Issue by clarklight** [leecrossley/cordova-plugin-directions#4]
Hi 

   I am just wondering if there is a possibility to support IOS as well? Thanks 

And also if this is on Phonegap Build? (Phonegap plugins?)

Thanks!

**Comment by leecrossley** [comment]
It's possible, [hire me](http://ilee.co.uk/contact-me/) if it's something you need urgently.

**Comment by leecrossley** [comment]
Regarding PhoneGap Build, I've added a note to the [readme](https://github.com/leecrossley/cordova-plugin-directions#phonegap-build)

**Comment by leecrossley** [comment]
This has been done, see #5 (props @starsasumi)
