### ISSUE TITLE
Not working on iOS 9

### ISSUE THREAD

**Issue by wsenjer** [leecrossley/cordova-plugin-directions#7]
Hello,
Thank you for sharing such a great plugin.

I tested on Android and it works as charm, but when I test it on iOS 9 it doesn't seem workin. I didn't test it on less than iOS 9 though. 

Could you please check on this?

**Comment by leecrossley** [comment]
`navigateToAddress` works but `navigateTo` throws:
> LaunchServices: ERROR: There is no registered handler for URL scheme (null)

I'll look into it.
